In [7]:
import math
import numpy as np

In [16]:
central = [0.2428, -1.40279, 1.95973]
theta = 136.829
scan_offset = 0.09
scan_distance_1 = 0.20
scan_distance_2 = -0.06

In [17]:
theta_tmp = ( theta - 90.0 ) / 180.0 * math.pi;

x_tmp = central [0];
y_tmp = central [1] + scan_offset * math.sin ( theta_tmp );
z_tmp = central [2] - scan_offset * math.cos ( theta_tmp );
scan_distance = scan_distance_1
x_s = x_tmp;
y_s = y_tmp - scan_distance * math.cos ( theta_tmp );
z_s = z_tmp - scan_distance * math.sin ( theta_tmp );
scan_distance = scan_distance_2 
x_e = x_tmp;
y_e = y_tmp + scan_distance * math.cos ( theta_tmp );
z_e = z_tmp + scan_distance * math.sin ( theta_tmp );

print ( theta, x_s, y_s, z_s, x_e, y_e, z_e)

(136.829, 0.2428, -1.4739872595151517, 1.7522909722411617, 0.2428, -1.3782023319437253, 1.8543950742652064)


In [39]:
a = np.array( [0.246571, -1.58283, 1.56729] )
b = np.array( [0.246571, -1.48607, 1.69472] )
c = (a + b) / 2
print ( c[0], c[1] - scan_offset * math.sin ( theta_tmp ), c[2] + scan_offset * math.cos ( theta_tmp ))

(0.246571, -1.5996611635671412, 1.7068172954817988)


Test for transformation

In [9]:
a =  np.matrix( [[-0.0186231, -0.708675, 0.70529, -2.38854],
                 [-0.999794, 0.0188989, -0.00740985, 0.278318], 
                 [-0.00807802, -0.705283, -0.708881, 0.269597],
                 [0, 0, 0, 1]])
print (a)
b =  np.matrix( [[1,  0, 0, 0],
                 [0, -1, 0, 0], 
                 [0, 0, -1, 0],
                 [0, 0, 0, 1]])
print (b)
c =  np.matrix( [[-1,  0, 0, 0],
                 [0, -1, 0, 0], 
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]])
print (c)

[[-0.0186231  -0.708675    0.70529    -2.38854   ]
 [-0.999794    0.0188989  -0.00740985  0.278318  ]
 [-0.00807802 -0.705283   -0.708881    0.269597  ]
 [ 0.          0.          0.          1.        ]]
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]
[[-1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]]


In [10]:
print ( np.min( np.abs ( a[0, 0:3] ) ) )
if np.abs ( a[0, 0] ) == np.min ( np.abs ( a[0, 0:3] ) ) and a[0, 1] < 0 and a[0, 2] > 0:
    print ( b * a )
    print ( c * b * a )

0.0186231
[[-0.0186231  -0.708675    0.70529    -2.38854   ]
 [ 0.999794   -0.0188989   0.00740985 -0.278318  ]
 [ 0.00807802  0.705283    0.708881   -0.269597  ]
 [ 0.          0.          0.          1.        ]]
[[ 0.0186231   0.708675   -0.70529     2.38854   ]
 [-0.999794    0.0188989  -0.00740985  0.278318  ]
 [ 0.00807802  0.705283    0.708881   -0.269597  ]
 [ 0.          0.          0.          1.        ]]
